/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kampusku.ui;

import com.kampusku.dao.DosenDAO;
import com.kampusku.dao.KelasDAO;
import com.kampusku.dao.MahasiswaDAO;
import com.kampusku.model.Dosen;
import com.kampusku.model.Mahasiswa;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        lblLogoMhs.setIcon(new ImageIcon(getClass().getResource("/images/user.png")));
        lblLogoDosen.setIcon(new ImageIcon(getClass().getResource("/images/user.png")));
        lblLogoKelas.setIcon(new ImageIcon(getClass().getResource("/images/course.png")));

        setLocationRelativeTo(null);
        loadJmlDataMhsDosenKelas();
        loadDataMahasiswa();
        loadDataDosen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        navJadwalKuliah = new javax.swing.JLabel();
        navDashboard = new javax.swing.JLabel();
        navDaftarMK = new javax.swing.JLabel();
        navLogout = new javax.swing.JLabel();
        navDaftarKelas = new javax.swing.JLabel();
        navDataMhs = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogoMhs = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jmlMhs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogoKelas = new javax.swing.JLabel();
        jmlKelas = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblLogoDosen = new javax.swing.JLabel();
        jmlDosen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataMhs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataDosen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Kampusku - Dahsboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(124, 68, 79));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 230));

        navJadwalKuliah.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navJadwalKuliah.setForeground(new java.awt.Color(204, 204, 204));
        navJadwalKuliah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navJadwalKuliah.setText("Jadwal Kuliah");
        navJadwalKuliah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navJadwalKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navJadwalKuliahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navJadwalKuliahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navJadwalKuliahMouseExited(evt);
            }
        });

        navDashboard.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navDashboard.setForeground(java.awt.Color.white);
        navDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navDashboard.setText("Dashboard");
        navDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDashboardMouseExited(evt);
            }
        });

        navDaftarMK.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navDaftarMK.setForeground(new java.awt.Color(204, 204, 204));
        navDaftarMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navDaftarMK.setText("Daftar MK");
        navDaftarMK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navDaftarMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navDaftarMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDaftarMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDaftarMKMouseExited(evt);
            }
        });

        navLogout.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navLogout.setForeground(new java.awt.Color(204, 204, 204));
        navLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navLogout.setText("Logout");
        navLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLogoutMouseExited(evt);
            }
        });

        navDaftarKelas.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navDaftarKelas.setForeground(new java.awt.Color(204, 204, 204));
        navDaftarKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navDaftarKelas.setText("Daftar Kelas");
        navDaftarKelas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navDaftarKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navDaftarKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDaftarKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDaftarKelasMouseExited(evt);
            }
        });

        navDataMhs.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        navDataMhs.setForeground(new java.awt.Color(204, 204, 204));
        navDataMhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navDataMhs.setText("Data Mahasiswa");
        navDataMhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navDataMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navDataMhsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDataMhsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDataMhsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(navDaftarKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(navDaftarMK, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(navJadwalKuliah)
                                    .addComponent(navDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addComponent(navDataMhs, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addComponent(navLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(navDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navJadwalKuliah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navDaftarMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navDaftarKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navDataMhs)
                .addGap(192, 192, 192)
                .addComponent(navLogout)
                .addGap(24, 24, 24))
        );

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        header.setBackground(new java.awt.Color(239, 243, 234));

        jLabel6.setBackground(new java.awt.Color(239, 243, 234));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DASHBOARD KAMPUSKU");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 620, 60));

        main.setBackground(new java.awt.Color(239, 243, 234));

        jPanel2.setBackground(new java.awt.Color(0, 123, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(160, 120));
        jPanel2.setMinimumSize(new java.awt.Dimension(160, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoMhs.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lblLogoMhs.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(lblLogoMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 70));

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total Mahasiswa");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jmlMhs.setFont(new java.awt.Font("Poppins Medium", 1, 36)); // NOI18N
        jmlMhs.setForeground(new java.awt.Color(51, 51, 51));
        jmlMhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlMhs.setText("12");
        jPanel2.add(jmlMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, -1));

        jPanel3.setBackground(new java.awt.Color(255, 193, 7));
        jPanel3.setMaximumSize(new java.awt.Dimension(160, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(160, 120));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Total Kelas");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        lblLogoKelas.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lblLogoKelas.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(lblLogoKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 70));

        jmlKelas.setFont(new java.awt.Font("Poppins Medium", 1, 36)); // NOI18N
        jmlKelas.setForeground(new java.awt.Color(51, 51, 51));
        jmlKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlKelas.setText("12");
        jPanel3.add(jmlKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, -1));

        jPanel4.setBackground(new java.awt.Color(40, 167, 69));
        jPanel4.setMaximumSize(new java.awt.Dimension(160, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(160, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Total Dosen");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        lblLogoDosen.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lblLogoDosen.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(lblLogoDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 70));

        jmlDosen.setFont(new java.awt.Font("Poppins Medium", 1, 36)); // NOI18N
        jmlDosen.setForeground(new java.awt.Color(51, 51, 51));
        jmlDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlDosen.setText("12");
        jPanel4.add(jmlDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, -1));

        tableDataMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, ""},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Email", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tableDataMhs);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Mahasiswa");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Data Dosen");

        tableDataDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Dosen", "Nama", "Email", "Nomor Telepon", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(tableDataDosen);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 620, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    // navDashboard    */
    private void loadJmlDataMhsDosenKelas() {
    // Mengambil jumlah mahasiswa, dosen, dan kelas dari database
        MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
        DosenDAO dosenDAO = new DosenDAO();
        KelasDAO kelasDAO = new KelasDAO();

        // Mendapatkan jumlah data mahasiswa, dosen, dan kelas
        int jumlahMahasiswa = mahasiswaDAO.getJumlahMahasiswa();
        int jumlahDosen = dosenDAO.getJumlahDosen();
        int jumlahKelas = kelasDAO.getJumlahKelas();

        jmlMhs.setText(String.valueOf(jumlahMahasiswa));
        jmlDosen.setText(String.valueOf(jumlahDosen));
        jmlKelas.setText(String.valueOf(jumlahKelas));
    }

    private void loadDataMahasiswa() {
        // Mengambil data mahasiswa dari database
        MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
        List<Mahasiswa> mahasiswaList = mahasiswaDAO.getAllMahasiswa();

        // Mendapatkan model tabel dari tabelDataMhs
        DefaultTableModel model = (DefaultTableModel) tableDataMhs.getModel();

        // Menghapus data lama di tabel
        model.setRowCount(0);

        // Menambahkan data mahasiswa ke dalam tabel
        for (Mahasiswa mahasiswa : mahasiswaList) {
            // Menambahkan baris data mahasiswa ke tabel
            model.addRow(new Object[]{
                mahasiswa.getNIM(),
                mahasiswa.getNamaMhs(),
                mahasiswa.getEmail(),
                mahasiswa.getAlamat()
            });
        }
    }

    private void loadDataDosen() {
        // Mengambil data dosen dari database
        DosenDAO dosenDAO = new DosenDAO();
        List<Dosen> dosenList = dosenDAO.getAllDosen();

        // Mendapatkan model tabel dari tabelDataDosen
        DefaultTableModel model = (DefaultTableModel) tableDataDosen.getModel();

        // Menghapus data lama di tabel
        model.setRowCount(0);

        // Menambahkan data dosen ke dalam tabel
        for (Dosen dosen : dosenList) {
            // Menambahkan baris data dosen ke tabel
            model.addRow(new Object[]{
                dosen.getKodeDosen(),
                dosen.getNamaDosen(),
                dosen.getEmail(),
                dosen.getNoTelepon(),
                dosen.getAlamat()
            });
        }
    }

    
    // navJadwalKuliah
    private void navJadwalKuliahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navJadwalKuliahMouseExited
        // TODO add your handling code here:
        navJadwalKuliah.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_navJadwalKuliahMouseExited

    private void navJadwalKuliahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navJadwalKuliahMouseEntered
        // TODO add your handling code here:
        navJadwalKuliah.setForeground(Color.WHITE);
    }//GEN-LAST:event_navJadwalKuliahMouseEntered

    // navDaftarMK
    private void navDaftarMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarMKMouseEntered
        // TODO add your handling code here:
        navDaftarMK.setForeground(Color.WHITE);
    }//GEN-LAST:event_navDaftarMKMouseEntered

    private void navDaftarMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarMKMouseExited
        // TODO add your handling code here:
        navDaftarMK.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_navDaftarMKMouseExited

    //navDaftarKelas
    private void navDaftarKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarKelasMouseEntered
        // TODO add your handling code here:
        navDaftarKelas.setForeground(Color.WHITE);
    }//GEN-LAST:event_navDaftarKelasMouseEntered
    
    private void navDaftarKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarKelasMouseExited
        // TODO add your handling code here:
        navDaftarKelas.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_navDaftarKelasMouseExited
    
    // navDataMhs
    private void navDataMhsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDataMhsMouseEntered
        // TODO add your handling code here:
        navDataMhs.setForeground(Color.WHITE);
    }//GEN-LAST:event_navDataMhsMouseEntered

    private void navDataMhsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDataMhsMouseExited
        // TODO add your handling code here:
        navDataMhs.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_navDataMhsMouseExited
    
    // navLogout
    private void navLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseEntered
        // TODO add your handling code here:
        navLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_navLogoutMouseEntered

    private void navLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseExited
        // TODO add your handling code here:
        navLogout.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_navLogoutMouseExited
    
    // Click event
    private void navLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseClicked
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_navLogoutMouseClicked

    private void navJadwalKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navJadwalKuliahMouseClicked
        // TODO add your handling code here:
        new JadwalKuliahFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_navJadwalKuliahMouseClicked

    private void navDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_navDashboardMouseEntered

    private void navDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_navDashboardMouseExited

    private void navDaftarMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarMKMouseClicked
        // TODO add your handling code here:
        new DaftarMKFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_navDaftarMKMouseClicked

    private void navDaftarKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDaftarKelasMouseClicked
        // TODO add your handling code here:
        new DaftarKelasFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_navDaftarKelasMouseClicked

    private void navDataMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDataMhsMouseClicked
        // TODO add your handling code here:
        new DataMhsFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_navDataMhsMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jmlDosen;
    private javax.swing.JLabel jmlKelas;
    private javax.swing.JLabel jmlMhs;
    private javax.swing.JLabel lblLogoDosen;
    private javax.swing.JLabel lblLogoKelas;
    private javax.swing.JLabel lblLogoMhs;
    private javax.swing.JPanel main;
    private javax.swing.JLabel navDaftarKelas;
    private javax.swing.JLabel navDaftarMK;
    private javax.swing.JLabel navDashboard;
    private javax.swing.JLabel navDataMhs;
    private javax.swing.JLabel navJadwalKuliah;
    private javax.swing.JLabel navLogout;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tableDataDosen;
    private javax.swing.JTable tableDataMhs;
    // End of variables declaration//GEN-END:variables
}
