/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kampusku.ui;

import com.kampusku.dao.KelasDAO;
import com.kampusku.dao.MahasiswaDAO;
import com.kampusku.model.Kelas;
import com.kampusku.model.Mahasiswa;
import java.awt.Color;
import java.util.Date;
import java.util.List;

/**
 *
 * @author ACER
 */
public class EditDataMhsFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditJadwalFrame
     */
    public EditDataMhsFrame(String data1) {
        initComponents();
        setLocationRelativeTo(null);
        loadDataMahasiswa(data1);
        loadKelasToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nimField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        noTeleponField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbKelas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tanggalLahirField = new javax.swing.JSpinner();
        btnSimpan = new javax.swing.JButton();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        errLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 243, 234));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 243, 234));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("EDIT DATA MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setBackground(new java.awt.Color(239, 243, 234));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tanggal Lahir");

        nimField.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nama Mahasiswa");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Kelas");

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nomor Telepon");

        tanggalLahirField.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1735352087813L), null, null, java.util.Calendar.DAY_OF_MONTH));

        btnSimpan.setBackground(new java.awt.Color(51, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        errLabel.setForeground(new java.awt.Color(255, 51, 51));
        errLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errLabel.setMinimumSize(new java.awt.Dimension(300, 20));
        errLabel.setPreferredSize(new java.awt.Dimension(300, 20));

        backLabel.setForeground(new java.awt.Color(51, 51, 51));
        backLabel.setText("<< BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(nimField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(emailField)
                    .addComponent(tanggalLahirField)
                    .addComponent(cmbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noTeleponField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(alamatField)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(backLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nimField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalLahirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTeleponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(backLabel))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(validasiInput()){
            if(ambilDataForm()){
                errLabel.setText("Data berhasil disimpan");
                errLabel.setForeground(Color.GREEN);
                errLabel.setVisible(true);
                new DataMhsFrame().setVisible(true);
                dispose();
            } else{
                errLabel.setText("Data gagal disimpan");
                errLabel.setForeground(Color.RED);
                errLabel.setVisible(true);
            }
        } 
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        new DataMhsFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backLabelMouseClicked
    
    private boolean validasiInput() {
        // Validasi NIM
        if (nimField.getText().isEmpty()) {
            errLabel.setText("NIM tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Nama
        if (namaField.getText().isEmpty()) {
            errLabel.setText("Nama tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Alamat
        if (alamatField.getText().isEmpty()) {
            errLabel.setText("Alamat tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Email
        if (emailField.getText().isEmpty()) {
            errLabel.setText("Email tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        } else if (!emailField.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            errLabel.setText("Format email tidak valid!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi No Telepon
        if (noTeleponField.getText().isEmpty()) {
            errLabel.setText("No Telepon tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        } else if (!noTeleponField.getText().matches("^[0-9]+$")) {
            errLabel.setText("No Telepon hanya boleh angka!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Tanggal Lahir
        if (tanggalLahirField.getValue() == null) {
            errLabel.setText("Tanggal Lahir tidak boleh kosong!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Jenis Kelamin
        if (cmbJenisKelamin.getSelectedItem() == null || cmbJenisKelamin.getSelectedItem().toString().isEmpty()) {
            errLabel.setText("Jenis Kelamin harus dipilih!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Validasi Kelas
        if (cmbKelas.getSelectedItem() == null || cmbKelas.getSelectedItem().toString().isEmpty()) {
            errLabel.setText("Kelas harus dipilih!");
            errLabel.setForeground(Color.RED);
            return false;
        }

        // Semua input valid
        return true;
    }
    
    private boolean ambilDataForm() {
        // Ambil data dari setiap field
        String nim = nimField.getText();
        String nama = namaField.getText();
        String alamat = alamatField.getText();
        String email = emailField.getText();
        String noTelepon = noTeleponField.getText();
        Date tanggalLahir = (Date) tanggalLahirField.getValue();
        String jenisKelamin = (String) cmbJenisKelamin.getSelectedItem();
        String kelas = (String) cmbKelas.getSelectedItem();
        Kelas objKelas = getKelasByNama(kelas);

        // Buat objek mahasiswa dengan data yang diambil
        Mahasiswa mahasiswa = new Mahasiswa(nim, objKelas.getKodeKelas(), nama, email, alamat, tanggalLahir, noTelepon, jenisKelamin);

        // Panggil DAO untuk update data mahasiswa
        MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();

        try {
            if (!mahasiswaDAO.updateMahasiswa(mahasiswa)) {
                errLabel.setText("Gagal memperbarui data mahasiswa!");
                errLabel.setForeground(Color.RED);
                return false;
            } else {
                errLabel.setText("Data mahasiswa berhasil diperbarui!");
                errLabel.setForeground(Color.GREEN);
                return true;
            }
        } catch (Exception e) {
            errLabel.setText("Terjadi kesalahan saat memperbarui data!");
            errLabel.setForeground(Color.RED);
            e.printStackTrace();
            return false;
        }
    }
    
    private Kelas getKelasByNama(String nama){
        KelasDAO kelasDAO = new KelasDAO();
        return kelasDAO.getKelasByNama(nama);
    }
    
    private void loadKelasToComboBox() {
        KelasDAO kelasDAO = new KelasDAO();
        List<Kelas> kelasList = kelasDAO.getAllKelas();  // Mendapatkan semua data kelas

        cmbKelas.removeAllItems();  // Menghapus item yang ada sebelumnya di ComboBox
        for (Kelas kelas : kelasList) {
            cmbKelas.addItem(kelas.getNamaKelas());  // Menambahkan nama kelas ke ComboBox
        }
    }

    private void loadDataMahasiswa(String nim) {
        MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
        Mahasiswa mahasiswa = mahasiswaDAO.getOneMahasiswa(nim); // Pastikan ada metode di DAO untuk mengambil data berdasarkan NIM

        if (mahasiswa != null) {
            // Isi field dengan data mahasiswa
            nimField.setText(mahasiswa.getNIM());
            namaField.setText(mahasiswa.getNamaMhs());
            alamatField.setText(mahasiswa.getAlamat());
            emailField.setText(mahasiswa.getEmail());
            noTeleponField.setText(mahasiswa.getNoTelepon());

            // Set tanggal lahir menggunakan JSpinner dengan SpinnerDateModel
            tanggalLahirField.setValue(mahasiswa.getTglLahir()); // setValue menerima objek Date

            KelasDAO kelasDAO = new KelasDAO();
            Kelas kelas = kelasDAO.getOneKelas(mahasiswa.getKodeKelas());

            cmbJenisKelamin.setSelectedItem(mahasiswa.getJenisKelamin());
            cmbKelas.setSelectedItem(kelas.getNamaKelas());  // Memilih kelas sesuai mahasiswa
        } else {
            errLabel.setText("Data mahasiswa tidak ditemukan!");
            errLabel.setForeground(Color.RED);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nimField;
    private javax.swing.JTextField noTeleponField;
    private javax.swing.JSpinner tanggalLahirField;
    // End of variables declaration//GEN-END:variables
}
